### ISSUE TITLE
Invalid Pem file

### ISSUE THREAD

**Issue by impuulse** [bryglen/yii2-apns-gcm#12]
but file path writen in config and its exist:

'apns' => [
            'class' => 'bryglen\apnsgcm\Apns',
            'environment' => \bryglen\apnsgcm\Apns::ENVIRONMENT_SANDBOX,
            'pemFile' => '@app/apnscert/ck.pem',
            // 'retryTimes' => 3,
            'options' => [
                'sendRetryTimes' => 5
            ]
        ],

**Comment by bryglen** [comment]
you shouldn't use alias. alias does not support. you should use complete path such as `dirname(__FILE) . '/../apnscert/ck.pem'`
