### ISSUE TITLE
The requested package duccio/apns-php could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by vishnupriyam** [bryglen/yii2-apns-gcm#13]
Error while doing composer update

    The requested package duccio/apns-php could not be found in any version, there may be a typo in the package name.

**Comment by bryglen** [comment]
please check your composer.json

**Comment by vishnupriyam** [comment]
I gave the instructions as in the readme here .

**Comment by bryglen** [comment]
use 1.0.4
