### ISSUE TITLE
Unable to connect to 'tls://gateway.sandbox.push.apple.com:2195':  (0)

### ISSUE THREAD

**Issue by janfrs** [bryglen/yii2-apns-gcm#14]
I'm getting unable to connect, my pemFile is fine, and on demo site, the same error occurrs.

error is traced to:
[file] => /home/vagrant/www/elo-jur-dico-web/vendor/duccio/apns-php/ApnsPHP/Abstract.php                                              
[line] => 334                                                                                                                         
[function] => _connect                                                                                                                
[class] => ApnsPHP_Abstract

**Comment by janfrs** [comment]
I've found out that the problem was that my pemFile required a passphrase and there's no how to set certificate passphrase on module's configurations...

**Comment by bryglen** [comment]
```
'apns' => [
        'class' => 'bryglen\apnsgcm\Apns',
        'environment' => \bryglen\apnsgcm\Apns::ENVIRONMENT_SANDBOX,
        'pemFile' => dirname(__FILE__).'/apnssert/apns-dev.pem',
        // 'retryTimes' => 3,
        'options' => [
            'providerCertificatePassphrase' => ''your_password_here'
        ]
    ],
```

**Comment by janfrs** [comment]
Wow, that worked, thanks
