### ISSUE TITLE
gcm library is old

### ISSUE THREAD

**Issue by marcinskubala** [bryglen/yii2-apns-gcm#15]
GCM doesn't work with the previous lib.
"php-gcm/php-gcm": "1.1.*" -> "php-gcm/php-gcm": "^1.1.1"
sendMulti() -> send()

**Comment by bryglen** [comment]
feel free to update it and make a PR

**Comment by marcinskubala** [comment]
Hi, I don't have permission to push changes.

**Comment by bryglen** [comment]
you need to fork and make a PR

**Comment by bryglen** [comment]
fixed in this PR

https://github.com/bryglen/yii2-apns-gcm/pull/18
