### ISSUE TITLE
Cannot install by adding it with in composer.json

### ISSUE THREAD

**Issue by TNChalise** [bryglen/yii2-apns-gcm#2]
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "bryglen/yii2-apns-gcm": "1.0.0"  or "dev-master"
    },

Problem 1
    - Installation request for bryglen/yii2-apns-gcm dev-master -> satisfiable by bryglen/yii2-apns-gcm[dev-master].
    - bryglen/yii2-apns-gcm dev-master requires duccio/apns-php dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I don't want to re-correct the stability parameters in my composer.json.

**Comment by Spollyy** [comment]
Solution is pretty simple, this package needs "duccio/apns-php dev-master" to be installed. 
Just add "duccio/apns-php" : "dev-master" in your composer.json, and run php composer.phar update
after that, just try to install package again. It should work

**Comment by bryglen** [comment]
use 1.0.1 now. it should solve the problem

**Comment by ademahendra** [comment]
I've got this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bryglen/yii2-apns-gcm 1.0.1 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by bryglen** [comment]
how did you set your composer.json?

the packagist is recognizing the 1.0.1

https://packagist.org/packages/bryglen/yii2-apns-gcm

**Comment by ademahendra** [comment]
Sorry, my mistake... 
Now everything running well..
My composer.json is the problem and now has been fixed.
Thanks
