### ISSUE TITLE
'call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by tomekorfant** [bryglen/yii2-apns-gcm#27]
Hi mate, 

I get this error:
[-][-][error][yii\base\ErrorException:2] exception 'yii\base\ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'ApnsPHP_Message' does not have a method 'sound'' in ./vendor/bryglen/yii2-apns-gcm/Apns.php:184

in class Apns.php at 180 lone is bug.
`
            if (strpos($method, 'set') === false) {
                $message = 'set' . ucfirst($method);
            }
`
Instead "$message = ..." should be "$method = ..."

Thanks.

**Comment by bryglen** [comment]
```
'options' => [
            'sound' => 'yoursound.wav'
        ]
```

**Comment by tomekorfant** [comment]
I was not setting sound. You have bug at 180 line if class Apns.php.
Same bug has been at 136 fixed here: https://github.com/bryglen/yii2-apns-gcm/commit/1df8e4a441132d33da28b4e264b9c8b8f4694afb

**Comment by bryglen** [comment]
is it still an issue?
