### ISSUE TITLE
How to get errors in model/controller

### ISSUE THREAD

**Issue by a-komarev** [bryglen/yii2-apns-gcm#3]
How to get sending operation errors/debug information in Model/Controller which using your extension?

**Comment by bryglen** [comment]
https://github.com/bryglen/yii2-apns-gcm/blob/master/Apns.php#L152

**Comment by a-komarev** [comment]
I've used `ApnsGcm` class and didn't have any errors ever .

**Comment by bryglen** [comment]
what is your code?

**Comment by a-komarev** [comment]
```php
$pushToken = 'UserTokenHere';
$message = $messageModel->body;

$apnsGcm = Yii::$app->apnsGcm;
$apnsGcm->send(
    \bryglen\apnsgcm\ApnsGcm::TYPE_GCM,
    $pushToken,
    $message,
    [
        'customerProperty' => 1
    ],
    [
        'timeToLive' => 3
    ]
);
$error = $apnsGcm->error;
```

**Comment by bryglen** [comment]
supposedly that's how it works if there is any error. I just pull info from the APNS library.

**Comment by a-komarev** [comment]
But errors are exists when I'm placing debug traces in APNS library. Sorry, don't have enough time now to provide more information and test cases.

**Comment by bryglen** [comment]
not sure either. I am only using a wrapper for the APNS and GCM. maybe tried to do some debugging in the main library itself

**Comment by bryglen** [comment]
fixed on https://github.com/bryglen/yii2-apns-gcm/pull/4
