### ISSUE TITLE
old version of php-gcm/php-gcm

### ISSUE THREAD

**Issue by marcinskubala** [bryglen/yii2-apns-gcm#9]
php-gcm/php-gcm should be in 1.1.0 version.

**Comment by bryglen** [comment]
is it safe to upgrade to 1.1.0?

**Comment by marcinskubala** [comment]
yep, there is only a small change. I use your lib with php-gcm 1.1 and it works fine.

**Comment by bryglen** [comment]
use `bryglen/yii2-apns-gcm": "1.0.2`
